# Example docker-compose with HTTPS support
services:
  # Your existing API service
  api:
    image: node:20-bookworm-slim
    container_name: video-editor-api
    working_dir: /workspace/server
    volumes:
      - ./server:/workspace/server
      - ./client/dist:/workspace/server/public
      - ./server/build-info.json:/workspace/server/build-info.json:ro
    command: bash -lc "apt-get update && apt-get install -y --no-install-recommends ffmpeg ca-certificates && rm -rf /var/lib/apt/lists/* && node src/index.js"
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"  # Only expose internally
    restart: unless-stopped

  # Nginx reverse proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: video-editor-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt  # SSL certificates
    depends_on:
      - api
    restart: unless-stopped