AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB table for CAB432 Video Editor application'

Parameters:
  QUTUsername:
    Type: String
    Default: 'n11590041'
    Description: 'QUT username for resource naming'
    
  Environment:
    Type: String
    Default: 'prod'
    AllowedValues: ['dev', 'test', 'prod']
    Description: 'Environment name'

Resources:
  VideoEditorTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${QUTUsername}-video-editor-data'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: CAB432-VideoEditor
        - Key: Owner
          Value: !Ref QUTUsername

Outputs:
  TableName:
    Description: 'DynamoDB table name'
    Value: !Ref VideoEditorTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'
      
  TableArn:
    Description: 'DynamoDB table ARN'
    Value: !GetAtt VideoEditorTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TableArn'
      
  StreamArn:
    Description: 'DynamoDB stream ARN'
    Value: !GetAtt VideoEditorTable.StreamArn
    Export:
      Name: !Sub '${AWS::StackName}-StreamArn'